### ISSUE TITLE
to-do before 2.1.0 release

### ISSUE THREAD

**Issue by saxamaphone69** [saxamaphone69/ss16#9]
## initial list
- [ ] oneechan support
- [ ] 4chan x 100% support
- [x] icons/header links slightly transparent unless hovered/active
- [ ] catalogue (hover to expand the card / replies)
- [ ] consolidate code
- [ ] lint etc.
- [ ] comment code appropriately
- [ ] `@media`
- [x] full usercss variable support

officially coming soon<sup>tm</sup>

## comments list
- [x] `webm` on `.io` site needs to be trimmed
- [x] support retina display (this is currently solved by blocking `js` on 4chan)
<img width="1024" alt="screen shot 2018-02-18 at 5 43 25 pm" src="https://user-images.githubusercontent.com/877480/36349102-60902ca2-14d3-11e8-9be1-c00bc165258a.png">

- [x] `.postInfo { padding-right: 2.5rem; )` means that menu and hiders wont appear over long subjects or multiple backlinks
- [x] `.postInfo` size changes 3 times, depending on content - not to mention when the subject overflows:

![postinfo](https://user-images.githubusercontent.com/877480/42719702-83347f22-875d-11e8-9747-2eb717efa2b3.png)
![longpost](https://user-images.githubusercontent.com/877480/42719710-beda4a66-875d-11e8-837c-995fe1240983.png)

- [x] with the domain split, the bottom full board list didn't make the switch

![image](https://user-images.githubusercontent.com/877480/48975706-018f5c80-f0cb-11e8-958d-a561cd113864.png)

getting the list from the 4chan homepage would be cool

![image](https://user-images.githubusercontent.com/877480/48975718-5af78b80-f0cb-11e8-808f-f3f95472df1d.png)

- [x] oh, `2.1.0` will probably feature full customisation via `usercss` settings (full width replies, colours, padding and margin being either 'comfortable' or 'compact', and whatever else should be user defined)

![image](https://user-images.githubusercontent.com/877480/49322689-c62add00-f565-11e8-8d57-baa6b857d44b.png)

- [x] post info/backlinks change size when they are inlined, probably because i make `.postMessage { font-size: 1.1rem; }` or whatever it is
- [ ] sidedish needs a minified version for publishing
- [ ] `#archive-board-select` should be moved to under the `legend` as opposed to the side
- [x] when thread watcher/qr is active - the icon should reflect that
- [x] normal backlinks look whack
- [ ] have `sidedish.user.js` manage:
   - oneechan support (blocks the default styles, should have a message that appears)
   - no 4chan x support
   - 4chan extension support

- [x] specify that font and banners need to be installed with the `https://boards\.4chan(?:nel)?\.org.*` regex, or include these in mozilla format instead and have stylus import

## other issues?
food for thought:
- material icons v42 woff2 file from google: 57 KB, takes ~40 ms
  - now, if we were to only grab the SVGs of the icons we needed, it would be about ~10 KB for ~40 icons
  - this would add 10 KB to ss16, even minified (right?)
  - should still be able to control colour/size via custom properties (right?)

- custom properties like ``--text-hint-on-background` or whatever aren't used
  - using `stylus` functions would eliminate the need for `--red-50/300/500/700`

**Comment by saxamaphone69** [comment]
- [ ] `webm` on `.io` site needs to be trimmed

**Comment by saxamaphone69** [comment]
<img width="1024" alt="screen shot 2018-02-18 at 5 43 25 pm" src="https://user-images.githubusercontent.com/877480/36349102-60902ca2-14d3-11e8-9be1-c00bc165258a.png">

 - [ ] support retina display

**Comment by saxamaphone69** [comment]
`.postInfo { padding-right: 2.5rem; )` means that menu and hiders wont appear over long subjects or multiple backlinks

**Comment by saxamaphone69** [comment]
![postinfo](https://user-images.githubusercontent.com/877480/42719702-83347f22-875d-11e8-9747-2eb717efa2b3.png)

`.postInfo` size changes 3 times, depending on content - not to mention when the subject overflows:

![longpost](https://user-images.githubusercontent.com/877480/42719710-beda4a66-875d-11e8-837c-995fe1240983.png)

**Comment by saxamaphone69** [comment]
- [ ] with the domain split, the bottom full board list didn't make the switch

![image](https://user-images.githubusercontent.com/877480/48975706-018f5c80-f0cb-11e8-958d-a561cd113864.png)

getting the list from the 4chan homepage would be cool

![image](https://user-images.githubusercontent.com/877480/48975718-5af78b80-f0cb-11e8-808f-f3f95472df1d.png)

**Comment by saxamaphone69** [comment]
oh, `2.1.0` will probably feature full customisation via `usercss` settings (full width replies, colours, padding and margin being either 'comfortable' or 'compact', and whatever else should be user defined)

**Comment by saxamaphone69** [comment]
![image](https://user-images.githubusercontent.com/877480/49322689-c62add00-f565-11e8-8d57-baa6b857d44b.png)

- [ ] post info/backlinks change size when they are inlined, probably because i make `.postMessage { font-size: 1.1rem; }` or whatever it is

**Comment by saxamaphone69** [comment]
- [ ] sidedish needs a minified version for publishing

**Comment by saxamaphone69** [comment]
food for thought:
- material icons v42 woff2 file from google: 57 KB, takes ~40 ms
  - now, if we were to only grab the SVGs of the icons we needed, it would be about ~10 KB for ~40 icons
  - this would add 10 KB to ss16, even minified (right?)
  - should still be able to control colour/size via custom properties (right?)

- custom properties like ``--text-hint-on-background` or whatever aren't used
  - using `stylus` functions would eliminate the need for `--red-50/300/500/700`

**Comment by saxamaphone69** [comment]
- [ ] `#archive-board-select` should be moved to under the `legend` as opposed to the side
- [ ] when thread watcher/qr is active - the icon should reflect that
- [ ] normal backlinks look whack

- [ ] have `sidedish.user.js` manage:
   - oneechan support (blocks the default styles, should have a message that appears)
   - no 4chan x support
   - 4chan extension support

**Comment by saxamaphone69** [comment]
may or may not have done stuff that was on this list, but will keep open
